### PR TITLE
updated UML to match master

### PR DESCRIPTION
**Pull request by MichaelSteer**
I want everyone to review this image and point out any glaring issues with it. I'm not merging this into master until I receive a review from at least 3 of the 5 of you.

image

### CODE REVIEW

**Comment by MichaelSteer** [comment]
Black - Activities connecting to activities
Blue - Models/Utilities/Controllers/Adapters communicating with Models/Utilities/Controllers/Adapters
Green - Anything communicating with GenerateRetrofit or CachingRetrofit

**Comment by MichaelSteer** [comment]
Im looking for big glaring things:

- Activity A uses fragment B but there's no association between B and A
- Class C doesn't link up to Interface D when they should

Im aware of little things:
- lots of functions that should return void don't have a return type specified.
- some things like inner classes are marked down like functions (mainly in Brendans GenerateRetrofit and Caching Retrofit classes). I have no idea how to properly mark those down with UML without creating a million other things

**Comment by MichaelSteer** [comment]
Disclaimer: By accepting this UML you are associating yourself with the loss of marks due to it

**Comment by MichaelSteer** [comment]
actually got rid of transparency

**Comment by CptJamesCook** [comment]
Seems fine to the best of my knowledge

**Comment by jtbakker** [comment]
The diagram looks fine as is, but we may need some aggregation relationships between our model classes and the activities/adapters.
* BidListAdapter has a list of Bids and a list of Users, so there should be an aggregation relationship between it and those two classes. The other adapters also have lists with Users, Tasks, ect.
* LoginActivity has a User list.
* ListTasksActivity has a Task list.
* ViewTaskActivity has a Bid List. Additionally, the "bidListAdapter" attribute is currently labelled as "ArrayList<Bid>" instead of "BidListAdapter".

**Pull request merged**
